sudo: required
services:
    - docker

before_install:
    - docker build -t sykeben/terraform-image .

# Terraform Plan, Apply, and Configure jobs.
jobs:
    include:
        - stage: plan
          script:
            - echo "Running plan on docker container..."
            - docker run -v $(pwd):/infra --env AZUSER=$AZ_USERNAME --env AZPASS=$AZ_PASSWORD sykeben/terraform-image plan -out planfile
        - stage: apply
          script:
            - echo "Running apply stage on docker container..."
            - docker run -v $(pwd):/infra --env AZUSER=$AZ_USERNAME --env AZPASS=$AZ_PASSWORD sykeben/terraform-plan apply "planfile"
        - stage: configure
          script:
            - echo "Running configure stage on docker container..."

stages:
    - plan
    - apply
    - configure

branches:
    only:
        - master