sudo: required
services:
    - docker
    - ansible

before_install:
    - docker pull sykeben/pipeline-az-terraform:1.0
    - docker build -t sykeben/terraform-plan .

# Terraform Plan, Apply, and Configure jobs.
jobs:
    include:
        - stage: plan
          script:
            - echo "Running plan on docker container..."
            - docker run --env AZUSER=AZ_LOGIN_USERNAME --env AZPASS=AZ_LOGIN_PASSWORD sykeben/terraform-plan
        - stage: apply
          script:
            - echo "Running apply stage on docker container..."
        - stage: configure
          script:
            - echo "Running configure stage on docker container..."

stages:
    - plan
    - apply
    - configure

branches:
    only:
        - master