language: bash
services:
    - docker

# Setup env variables for CI
env:
  - tf_version=0.12.19 tf_init_cli_options="-input=false" tf_validation_cli_options="" tf_plan_cli_options="-lock=false -input=false" tf_apply_cli_options="-auto-approve -input=false"

# Install dependencies
before_install:
  - echo $AZ_PASS
  - echo $AZ_TENANT
  - docker build -t az-terraform --build-arg pass=$AZ_PASS --build-arg tenant=$AZ_TENANT .

# Terraform Plan, Apply, and Configure jobs.
jobs:
    include:
        - stage: plan
          script:
            - docker run az-terraform ls -l
        - stage: apply
          script:
            - docker run az-terraform terraform init && terraform plan -o planfile && terraform apply planfile
          when: manual
        - stage: configure
          script:
            - echo "Running configure stage on docker container..."
          when: manual

stages:
    - plan
    - apply
    - configure

branches:
    only:
        - master